version: '3.8'

services:
  ml_api_1:
    build: ./api
    container_name: ml_api_1
    ports:
      - "8001:8000"

  ml_api_2:
    build: ./api
    container_name: ml_api_2
    ports:
      - "8002:8000"

  nginx:
    build: ./nginx
    container_name: nginx_lb
    ports:
      - "80:80"
    depends_on:
      - ml_api_1
      - ml_api_2 